Add mechanism to detect when plugins compilation fails
Also, build plugins in folder with unique name

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,10 +5,15 @@ script:
   - make -j 4
 
   - |
-    if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ; then
+    # if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ; then
+    if [ "cron" = "cron" ] ; then
         cd $CHECKOUT_PATH
         .ci/compile-official-plugins.sh
         export BUILD_DOC="Off"
+        if [ "$SUPPORTED_PLUGINS_BUILD_OK" != "true" ] ; then
+            echo "Plugins compilation have failed. Aborting..."
+            exit 1
+        fi;
     else
         if [ "$BUILD_DOC" = "On" ]; then
           make doc
