[git] failure must fail.

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -46,3 +46,5 @@ jobs:
           echo "git checkout ${{  github.head_ref }}"
           echo "git reset --hard gh-formatter"
           echo "git push"
+          exit 1
+#this last step must report fail.
